### ISSUE TITLE
SQLException

### ISSUE THREAD

**Issue by uvramana** [AzureADSamples/WebApp-MultiTenant-OpenIdConnect-DotNet#9]
Does this need a SQL connection. I see the following error while signing up. In the following code. I am using Visual Studio 2015 preview if that helps. Seems like the entity framework is not configure correctly for me.

        // POST: /Onboarding/SignUp
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SignUp([Bind(Include="ID,Name,AdminConsented")] Tenant tenant)
        {
            // generate a random value to identify the request
            string stateMarker = Guid.NewGuid().ToString();
            // store it in the temporary entry for the tenant, we'll use it later to assess if the request was originated from us
            // this is necessary if we want to prevent attackers from provisioning themselves to access our app without having gone through our onboarding process (e.g. payments, etc)
            tenant.IssValue = stateMarker;
            tenant.Created = DateTime.Now;
            db.Tenants.Add(tenant);  // exception from here.
            db.SaveChanges();

An exception of type 'System.Data.SqlClient.SqlException' occurred in EntityFramework.dll but was not handled in user code

Additional information: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 50 - Local Database Runtime error occurred. Cannot create an automatic instance. See the Windows Application event log for error details.

)

**Comment by uvramana** [comment]
I had to create a local DB and manually add the following in web.config to fix this issue.

  <connectionStrings>
    <add name="TodoListWebAppContext" connectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=TestDB;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" providerName="System.Data.SqlClient" />
  </connectionStrings>

**Comment by uvramana** [comment]
<connectionStrings>
    <add name="TodoListWebAppContext" connectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=TestDB;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" providerName="System.Data.SqlClient" />
  </connectionStrings>

**Comment by brentschmaltz** [comment]
User was able to move forward. Not a OIDC issue.
